### ISSUE TITLE
/login/callback 400 on staging

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#353]
I'm not sure why this is happening, but FYI on staging when people were testing today, I saw this:

```
ErrorResponse {
  status: 400,
  statusText: 'Bad Request',
  internal: true,
  data: 'Error: You made a GET request to "/login/callback" but did not provide a `loader` for route "routes/login/callback", so there is no way to handle the request.',
  error: Error: You made a GET request to "/login/callback" but did not provide a `loader` for route "routes/login/callback", so there is no way to handle the request.
      at getInternalRouterError (/app/build/server.js:37355:59)
      at loadRouteData (/app/build/server.js:36847:17)
      at queryImpl (/app/build/server.js:36735:30)
      at Object.queryRoute (/app/build/server.js:36707:28)
      at handleResourceRequestRR (/app/build/server.js:38305:44)
      at requestHandler (/app/build/server.js:38157:28)
      at /app/build/server.js:39317:32
      at Layer.handle [as handle_request] (/app/build/server.js:18001:9)
      at next (/app/build/server.js:18170:17)
      at next (/app/build/server.js:18166:11)
}
```

**Comment by humphd** [comment]
I haven't seen this for a while, closing for now.
