### ISSUE TITLE
Figure out EAUTH error for notifications on staging

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#444]
@SerpentBytes I tested the stuff you just landed for notifications, and it worked, but failed with an auth error we need to understand:

```
starchart_mycustomdomain.1.szxwrejre3cw@cudm-mgmt01dv.dcm.senecacollege.ca    | {"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Unable to send notification Invalid login: 550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]","response":"550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]","responseCode":550,"stack":"Error: Invalid login: 550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1502:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)","timestamp":"2023-03-25T23:04:27.339Z"}
starchart_mycustomdomain.1.szxwrejre3cw@cudm-mgmt01dv.dcm.senecacollege.ca    | {"code":"EAUTH","command":"AUTH LOGIN","level":"warn","message":"unable to send notification to david.humphrey@senecacollege.ca Invalid login: 550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]","response":"550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]","responseCode":550,"stack":"Error: Invalid login: 550 5.2.1 Mailbox cannot be accessed [YQBPR0101CA0096.CANPRD01.PROD.OUTLOOK.COM 2023-03-25T23:04:27.306Z 08DB2D73A9A12AAF]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1502:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)","timestamp":"2023-03-25T23:04:27.340Z"}
```

**Comment by SerpentBytes** [comment]
I found [this](https://github.com/nodemailer/nodemailer/issues/920).
It seems like the `transporter` is not configured correctly for our use case. Could you tell me the Steps to Reproduce this bug on the staging environment?

**Comment by humphd** [comment]
I don't think it's that, I think it's:

`“550 5 2 1 mail from refused spam site”`

**Comment by humphd** [comment]
I've emailed ITS about this, hoping for follow-up soon.

**Comment by humphd** [comment]
ITS has fixed the account on their end, and @SerpentBytes and I were able to get notifications working on staging!
