### ISSUE TITLE
Route error on staging

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#631]
@Eakam1007 is this related to the new layouts we did?  Seeing this on staging, not sure what triggered it.

```
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    | Error: Route "routes/__index/index" does not match URL "/"
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at getInternalRouterError (/app/build/server.js:37469:59)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at Object.queryRoute (/app/build/server.js:36748:17)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at handleDataRequestRR (/app/build/server.js:38283:44)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at requestHandler (/app/build/server.js:38257:28)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at /app/build/server.js:39423:32
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at Layer.handle [as handle_request] (/app/build/server.js:18022:9)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18191:17)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
starchart_mycustomdomain.2.hfv1jd3nab7e@cudm-mgmt01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    | Error: Route "routes/__index/index" does not match URL "/"
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at getInternalRouterError (/app/build/server.js:37469:59)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at Object.queryRoute (/app/build/server.js:36748:17)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at handleDataRequestRR (/app/build/server.js:38283:44)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at requestHandler (/app/build/server.js:38257:28)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at /app/build/server.js:39423:32
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at Layer.handle [as handle_request] (/app/build/server.js:18022:9)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18191:17)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
starchart_mycustomdomain.1.wcvqzfnngdf4@cudm-worker01dv.dcm.senecacollege.ca    |     at next (/app/build/server.js:18187:11)
```

**Comment by humphd** [comment]
We wonder if this is related to someone with a cached route trying to go back to it, and the server not having it now due the changes we made for Remix V2 route naming.  Closing.
